#!/usr/bin/env bash
#
# Inventory deployed IAM, secrets, regions and service configuration.
# TASK-LP-058.
#
# STRICTLY READ-ONLY. Every command below is a get/list/describe. Nothing here
# creates, updates or deletes. That is deliberate: the point of this ticket is
# to find out what is actually deployed before changing any of it, and an
# inventory script that can mutate is one typo away from an incident.
#
# The audit could not verify production configuration, billing mappings,
# tokens, backups or IAM because it had no operational access. This produces
# the evidence that closes that gap.
#
# Usage:
#   ./scripts/inventory-deployed-config.sh iep-and-thrive > ops/evidence/inventory-$(date +%F).md
#
# Requires: gcloud (authenticated), firebase CLI (authenticated), jq.
# Output is Markdown on stdout; diagnostics go to stderr.

set -uo pipefail

PROJECT="${1:-}"
if [[ -z "$PROJECT" ]]; then
  echo "usage: $0 <project-id>" >&2
  exit 2
fi

for tool in gcloud firebase jq; do
  command -v "$tool" >/dev/null 2>&1 || { echo "missing required tool: $tool" >&2; exit 1; }
done

# Run a read-only command, emitting a fenced block. Never aborts the whole run:
# a permission denial on one resource is itself a finding worth recording.
section() {
  local title="$1"; shift
  echo ""
  echo "### $title"
  echo ""
  echo '```'
  if ! "$@" 2>&1; then
    echo "(command failed — record whether this is a permissions gap or a"
    echo " genuinely absent resource; both are findings)"
  fi
  echo '```'
}

echo "# Deployed configuration inventory"
echo ""
echo "- **Project:** \`$PROJECT\`"
echo "- **Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "- **Generated by:** \`$(basename "$0")\` (read-only)"
echo ""
echo "> Read-only inventory. Compare against what the repository expects and"
echo "> record every difference — drift is the finding, not an error."

echo ""
echo "## Identity and access"

section "Project IAM policy (who can do what)" \
  gcloud projects get-iam-policy "$PROJECT" --format=json

section "Service accounts" \
  gcloud iam service-accounts list --project "$PROJECT" --format=json

echo ""
echo "> Review for: human accounts with Owner or Editor; service accounts with"
echo "> broader roles than the function they back needs; accounts belonging to"
echo "> people who have left; and any key that is user-managed rather than"
echo "> Google-managed. Least privilege is TASK-LP-058's exit criterion."

echo ""
echo "## Secrets"

section "Secret Manager secrets (names and metadata only — never values)" \
  gcloud secrets list --project "$PROJECT" --format=json

section "Secret IAM bindings" \
  bash -c "gcloud secrets list --project '$PROJECT' --format='value(name)' | while read -r s; do
             echo \"--- \$s\"; gcloud secrets get-iam-policy \"\$s\" --project '$PROJECT' --format=json
           done"

echo ""
echo "> Never paste a secret **value** into this report, a ticket, or a commit."
echo "> Names, versions, and who can access them are the inventory."

echo ""
echo "## Cloud Functions"

section "Deployed functions (region, runtime, trigger, service account)" \
  gcloud functions list --project "$PROJECT" --format=json

echo ""
echo "> Check every function's region against \`us-east1\` in"
echo "> \`lib/functions-config.ts\`, and its runtime against Node 22 in"
echo "> \`functions/package.json\`. The audit found the local runtime differs"
echo "> from the declared one; confirm what is actually deployed."
echo ">"
echo "> Also check which functions allow unauthenticated invocation. The six"
echo "> public onRequest endpoints are intentional; anything else on that list"
echo "> is a finding."

section "Public (allUsers) invoker bindings" \
  bash -c "gcloud functions list --project '$PROJECT' --format='value(name)' | while read -r f; do
             pol=\$(gcloud functions get-iam-policy \"\$f\" --project '$PROJECT' --format=json 2>/dev/null)
             if echo \"\$pol\" | jq -e '.bindings[]?.members[]? | select(. == \"allUsers\")' >/dev/null 2>&1; then
               echo \"PUBLIC: \$f\"
             fi
           done"

echo ""
echo "## Firestore and Storage"

section "Firestore databases" \
  gcloud firestore databases list --project "$PROJECT" --format=json

section "Firestore indexes (deployed)" \
  firebase firestore:indexes --project "$PROJECT"

section "Deployed Firestore rules" \
  firebase firestore:rules:get --project "$PROJECT"

section "Deployed Storage rules" \
  firebase storage:rules:get --project "$PROJECT"

section "Storage buckets" \
  gcloud storage buckets list --project "$PROJECT" --format=json

echo ""
echo "> **Diff the deployed rules against the repository.** They are the"
echo "> security boundary, and a difference means something was deployed out of"
echo "> band. This is the check that gates the TASK-LP-006 release."

echo ""
echo "## Backups"

section "Firestore backup schedules" \
  gcloud firestore backups schedules list --database='(default)' --project "$PROJECT" --format=json

section "Existing backups" \
  gcloud firestore backups list --project "$PROJECT" --format=json

echo ""
echo "> A configured schedule is not a verified restore. TASK-LP-059 rehearses"
echo "> the restore; this only records whether anything is being taken."

echo ""
echo "## Hosting"

section "Hosting sites" \
  firebase hosting:sites:list --project "$PROJECT"

section "Recent releases" \
  firebase hosting:channel:list --project "$PROJECT"

echo ""
echo "## Follow-up"
echo ""
echo "For each difference between this inventory and what the repository"
echo "expects, record: what differs, whether it is intentional, and the ticket"
echo "that will reconcile it. An unexplained difference in IAM, rules, or"
echo "public invoker bindings is a security finding, not a note."
